In [4]:
import pandas as pd
df_list = pd.read_html('https://www.wikidex.net/wiki/Lista_de_Pok%C3%A9mon_por_aparici%C3%B3n_en_la_vigesimosegunda_temporada')

In [5]:
len(df_list)

23

In [6]:
df_list[0]

                    Pokémon por aparición en el anime             Unnamed: 1
0   Serie El Comienzo Lista de Pokémon por aparici...                    NaN
1                                   Serie El Comienzo                    NaN
2   Lista de Pokémon por aparición en la primera t...                    NaN
3   Lista de Pokémon por aparición en la primera t...              T01 • T02
4   Serie Oro y Plata Lista de Pokémon por aparici...                    NaN
5                                   Serie Oro y Plata                    NaN
6   Lista de Pokémon por aparición en la tercera t...                    NaN
7   Lista de Pokémon por aparición en la tercera t...        T03 • T04 • T05
8   Serie Rubí y Zafiro Lista de Pokémon por apari...                    NaN
9                                 Serie Rubí y Zafiro                    NaN
10  Lista de Pokémon por aparición en la sexta tem...                    NaN
11  Lista de Pokémon por aparición en la sexta tem...  T06 • T07 • T08 • T09
12  Serie Diamante y Perla Lista de Pokémon por ap...                    NaN
13                             Serie Diamante y Perla                    NaN
14  Lista de Pokémon por aparición en la décima te...                    NaN
15  Lista de Pokémon por aparición en la décima te...  T10 • T11 • T12 • T13
16  Serie Negro y Blanco Lista de Pokémon por apar...                    NaN
17                               Serie Negro y Blanco                    NaN
18  Lista de Pokémon por aparición en la decimocua...                    NaN
19  Lista de Pokémon por aparición en la decimocua...        T14 • T15 • T16
20  Serie XY Lista de Pokémon por aparición en la ...                    NaN
21                                           Serie XY                    NaN
22  Lista de Pokémon por aparición en la decimosép...                    NaN
23  Lista de Pokémon por aparición en la decimosép...        T17 • T18 • T19
24  Serie Sol y Luna Lista de Pokémon por aparició...                    NaN
25                                   Serie Sol y Luna                    NaN
26  Lista de Pokémon por aparición en la vigésima ...                    NaN
27  Lista de Pokémon por aparición en la vigésima ...        T20 • T21 • T22
28  Serie Viajes Pokémon Lista de Pokémon por apar...                    NaN
29                               Serie Viajes Pokémon                    NaN
30  Lista de Pokémon por aparición en la vigesimot...                    NaN
31  Lista de Pokémon por aparición en la vigesimot...        T23 • T24 • T25
32  Otras animaciones Lista de Pokémon por aparici...                    NaN
33                                  Otras animaciones                    NaN
34  Lista de Pokémon por aparición en Pokémon Gene...                    NaN
35  Lista de Pokémon por aparición en Pokémon Gene...              GEN • EVO
36  Otras listas Lista de Pokémon con diferencias ...                    NaN
37                                       Otras listas                    NaN
38  Lista de Pokémon con diferencias de sexo por a...                    NaN
39  Lista de Pokémon con diferencias de sexo por a...         ♂/♀ • ★ • DMAX

In [17]:
df_list[1].to_csv('basededatosspace.csv', sep ='\t')

In [15]:
print(df_list[1].head())

   #     Pokémon Tipo(s) Tipo(s).1  \
0  1   Bulbasaur  Planta    Veneno
1  3    Venusaur  Planta    Veneno
2  5  Charmeleon   Fuego     Fuego
3  6   Charizard   Fuego   Volador
4  7    Squirtle    Agua      Agua

                        Episodios en los que aparece
0           EP215, EP225, EP226, EP227, EP257, EP270
1                                              EP250
2                                       EP223, EP224
3  EP250, EP254, EP255, EP256, EP271, EP272, EP27...
4                  EP218, EP269, EP270, EP274, EP275

In [16]:
df_list[1]['col'].str.get_dummies(sep=',')

KeyError: 'col'